### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 프로젝트 Post request
POST http://localhost:8080/projects
Content-Type: application/json
AccountId: 100

{
  "projectName": "프로젝트 이름",
  "project_status": "ACTIVE"
}

###
GET http://localhost:8080/projects
Content-Type: application/json
AccountId: 100

###
PUT http://localhost:8080/projects/1
Content-Type: application/json
AccountId: 100

{
  "projectId": 1,
  "projectName": "업데이트한 프로젝트 이름",
  "project_status": "ACTIVE"
}

###
GET http://localhost:8080/projects
Content-Type: application/json
AccountId: 10

###
PUT http://localhost:8080/projects/1
Content-Type: application/json
X-USER-ID: 10

{
  "projectId": 1,
  "projectName": "업데이트한 프로젝트 이름",
  "project_status": "ACTIVE"
}

###
GET http://localhost:8080/projects
Content-Type: application/json
X-USER-ID: 10

###
POST http://localhost:8080/projects/1/members/10
X-USER-ID: 100
Content-Type: application/json

###
POST http://localhost:8080/projects/2/members/10
Content-Type: application/json

###
DELETE http://localhost:8080/projects/1
Content-Type: application/json
X-USER-ID: 100


### milestone 등록
POST localhost:8080/projects/1/milestones
Content-Type: application/json

{
  "progress": "UI 설계"
}

### milestone 조회
GET localhost:8080/projects/1/milestones
Content-Type: application/json

### milestone 수정
PUT localhost:8080/projects/1/milestones/1
Content-Type: application/json

{
  "progress": "데이터베이스 설계 완료"
}

### milestone 수정 잘못된 milestone id
PUT localhost:8080/projects/1/milestones/1234
Content-Type: application/json

{
  "progress": "데이터베이스 설계 완료"
}

### milestone 삭제
DELETE localhost:8080/projects/1/milestones/1
Content-Type: application/json

### Comment 생성
POST http://localhost:8080/projects/1/tasks/1/comments
Content-Type: application/json

{
  "content": "댓글 내용"
}

### Comment 수정
PUT http://localhost:8080/projects/1/tasks/1/comments/1
Content-Type: application/json

{
  "content": "댓글 내용 수정"
}

### Comment 삭제
DELETE http://localhost:8080/projects/1/tasks/1/comments/1
Content-Type: application/json